In [10]:
import numpy as np

# Define the problem statement in matrix form
# Matrix A and vector b
A = np.array([
    [0, -1, -3, 4],
    [1, -2, 0, 3],
    [3, 2, -5, 0],
    [4, 3, -5, 0]
])
b = np.array([-5, -4, 12, 5])

# Solve the system using Cramer's Rule without using loops
def solve_cramers_no_loops(A, b):
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0):
        raise ValueError("Matrix is singular, the system has no unique solution.")
    
    # Replace columns and calculate determinants using slicing
    dets = np.array([
        np.linalg.det(np.column_stack([A[:, :i], b, A[:, i + 1:]]))
        for i in range(A.shape[1])
    ])
    
    # Compute the solution vector
    x = dets / det_A
    return x

# Solve the system using numpy.linalg.solve
def solve_numpy_linalg(A, b):
    return np.linalg.solve(A, b)

# Compute solutions
solution_cramers = solve_cramers_no_loops(A, b)
solution_numpy = solve_numpy_linalg(A, b)

# Validate solutions using numpy.allclose
is_close = np.allclose(solution_cramers, solution_numpy)

# Outputs
print("Solution using Cramer's Rule:", solution_cramers)
print("Solution using numpy.linalg.solve:", solution_numpy)
print("Solutions match:", is_close)


Solution using Cramer's Rule: [ 1. -8. -5. -7.]
Solution using numpy.linalg.solve: [ 1. -8. -5. -7.]
Solutions match: True


In [11]:
import numpy as np

# Task 3: Calculate the matrix expression (A^2 - B^2)(A + B)
def calculate_matrix_expression(A, B):
    """
    Calculate the matrix expression: (A^2 - B^2)(A + B)
    """
    # Compute A^2 and B^2
    A_squared = np.dot(A, A)
    B_squared = np.dot(B, B)
    
    # Compute the expression (A^2 - B^2)(A + B)
    result = np.dot((A_squared - B_squared), (A + B))
    return result

# Task 4: Solve the matrix equation using an inverse matrix and validate
def solve_matrix_equation(X, RHS):
    """
    Solve the matrix equation X * Coefficient_Matrix = Result_Matrix
    using an inverse matrix and validate with numpy.linalg.solve().
    """
    # Solve using the inverse of X
    inverse_X = np.linalg.inv(X)
    solution_inverse = np.dot(inverse_X, RHS)

    # Solve using numpy.linalg.solve
    solution_linalg = np.linalg.solve(X, RHS)

    # Validate the solutions
    is_close = np.allclose(solution_inverse, solution_linalg)

    return solution_inverse, solution_linalg, is_close

# Given Matrices for Task 3
A = np.array([[7, 2, 0], [-7, -2, 1], [1, 1, 0]])
B = np.array([[0, 2, 3], [1, 0, -2], [3, 1, 1]])

# Calculate the matrix expression
matrix_expression = calculate_matrix_expression(A, B)

# Given matrices for Task 4
X = np.array([
    [2, 1, 3],
    [1, -2, 0],
    [4, -3, 0]
])
RHS = np.array([
    [22, -14, 3],
    [6, -7, 0],
    [11, 3, 15]
])

# Solve the matrix equation and validate
solution_inverse, solution_linalg, validation = solve_matrix_equation(X, RHS)

# Display Results
print("Matrix Expression (Task 3):")
print(matrix_expression)

print("\nSolution to Matrix Equation (Task 4) using Inverse Matrix:")
print(solution_inverse)

print("\nSolution to Matrix Equation (Task 4) using numpy.linalg.solve:")
print(solution_linalg)

print("\nValidation (Task 4): Solutions Match:", validation)


Matrix Expression (Task 3):
[[ 138   88   68]
 [-154 -100  -78]
 [ -14  -16  -12]]

Solution to Matrix Equation (Task 4) using Inverse Matrix:
[[  0.8          5.4          6.        ]
 [ -2.6          6.2          3.        ]
 [  7.66666667 -10.33333333  -4.        ]]

Solution to Matrix Equation (Task 4) using numpy.linalg.solve:
[[  0.8          5.4          6.        ]
 [ -2.6          6.2          3.        ]
 [  7.66666667 -10.33333333  -4.        ]]

Validation (Task 4): Solutions Match: True
